In [1]:
import os
import pandas as pd
import zipfile
import pyarrow.parquet as pq
import pyarrow as pa

# Data for Phamacy registration
# https://www.pharmacyregulation.org/registers

# Data source from https://geoportal.statistics.gov.uk/datasets/265778cd85754b7e97f404a1c63aea04/about

curDir = os.getcwd()
#zf = zipfile.ZipFile(curDir + '/ONSPD_AUG_2024.zip')
zf = zipfile.ZipFile(curDir + '/ONSPD_FEB_2025.zip')
text_files = zf.infolist()

print ("Uncompressing and reading data... ")
#print(text_files)

Uncompressing and reading data...

In [10]:
#import polars as pl
list_ = []
alist_ = []
clist_ = []
nlist_ = []
out = "combined.parquet"
writer = None
for text_file in text_files:
    #Define columns of the csv reading
    colhd = ['pcd','pcd2','pcds','dointr','doterm','oscty','ced','oslaua','osward','parish','usertype','oseast1m','osnrth1m','osgrdind','oshlthau','nhser','ctry',\
             'rgn','streg','pcon','eer','teclec','ttwa','pct','itl','statsward','oa01','casward','npark','lsoa01','msoa01','ur01ind','oac01','oa11','lsoa11','msoa11',\
             'wz11','sicbl','bua22','ru11ind','oac11','lat','long','lep1','lep2','pfa','imd','calncv','icb','oa21','lsoa21','msoa21']

    # Session of main csv files
    # print(text_file.filename)
    if text_file.filename.endswith("csv"):
        if text_file.filename.startswith("Data/multi_csv/"):
            # Start row in 2nd row of each csv as it is huge size. It could saving more memory in process rather than handle 1st row as header.
            df = pd.read_csv(zf.open(text_file.filename), skiprows=[0], names=colhd, dtype=str)
            list_.append(df)
            
df = pd.concat(list_)

In [11]:
df.head(10)

,pcd,pcd2,pcds,dointr,doterm,oscty,ced,oslaua,osward,parish,...,long,lep1,lep2,pfa,imd,calncv,icb,oa21,lsoa21,msoa21
0,AB1 0AA,AB1 0AA,AB1 0AA,198001,199606,S99999999,S99999999,S12000033,S13002843,S99999999,...,-2.242851,S99999999,NaN,S23000009,6715,S99999999,S99999999,S00137176,S01013490,S02002516
1,AB1 0AB,AB1 0AB,AB1 0AB,198001,199606,S99999999,S99999999,S12000033,S13002843,S99999999,...,-2.246308,S99999999,NaN,S23000009,6715,S99999999,S99999999,S00137176,S01013490,S02002516
2,AB1 0AD,AB1 0AD,AB1 0AD,198001,199606,S99999999,S99999999,S12000033,S13002843,S99999999,...,-2.248342,S99999999,NaN,S23000009,6715,S99999999,S99999999,S00137176,S01013490,S02002516
3,AB1 0AE,AB1 0AE,AB1 0AE,199402,199606,S99999999,S99999999,S12000034,S13002864,S99999999,...,-2.255708,S99999999,NaN,S23000009,5069,S99999999,S99999999,S00138891,S01013856,S02002577
4,AB1 0AF,AB1 0AF,AB1 0AF,199012,199207,S99999999,S99999999,S12000033,S13002843,S99999999,...,-2.258102,S99999999,NaN,S23000009,6253,S99999999,S99999999,S00137241,S01013487,S02002515
5,AB1 0AG,AB1 0AG,AB1 0AG,199012,199207,S99999999,S99999999,S12000033,S13002843,S99999999,...,-2.267513,S99999999,NaN,S23000009,4691,S99999999,S99999999,S00137245,S01013482,S02002515
6,AB1 0AJ,AB1 0AJ,AB1 0AJ,198001,199606,S99999999,S99999999,S12000033,S13002843,S99999999,...,-2.252854,S99999999,NaN,S23000009,6715,S99999999,S99999999,S00137219,S01013490,S02002516
7,AB1 0AL,AB1 0AL,AB1 0AL,198001,199606,S99999999,S99999999,S12000033,S13002843,S99999999,...,-2.254688,S99999999,NaN,S23000009,6253,S99999999,S99999999,S00137184,S01013487,S02002515
8,AB1 0AN,AB1 0AN,AB1 0AN,198001,199606,S99999999,S99999999,S12000033,S13002843,S99999999,...,-2.245483,S99999999,NaN,S23000009,6715,S99999999,S99999999,S00137194,S01013490,S02002516
9,AB1 0AP,AB1 0AP,AB1 0AP,198001,199606,S99999999,S99999999,S12000033,S13002843,S99999999,...,-2.245768,S99999999,NaN,S23000009,6715,S99999999,S99999999,S00137194,S01013490,S02002516

In [12]:
df.size

141050260

In [4]:
## Delete all row original as header
df = df[df["pcd"] != "pcd"]

In [5]:
df.head(10)

,pcd,pcd2,pcds,dointr,doterm,oscty,ced,oslaua,osward,parish,...,long,lep1,lep2,pfa,imd,calncv,icb,oa21,lsoa21,msoa21
0,AB1 0AA,AB1 0AA,AB1 0AA,198001,199606,S99999999,S99999999,S12000033,S13002843,S99999999,...,-2.242851,S99999999,NaN,S23000009,6715,S99999999,S99999999,S00137176,S01013490,S02002516
1,AB1 0AB,AB1 0AB,AB1 0AB,198001,199606,S99999999,S99999999,S12000033,S13002843,S99999999,...,-2.246308,S99999999,NaN,S23000009,6715,S99999999,S99999999,S00137176,S01013490,S02002516
2,AB1 0AD,AB1 0AD,AB1 0AD,198001,199606,S99999999,S99999999,S12000033,S13002843,S99999999,...,-2.248342,S99999999,NaN,S23000009,6715,S99999999,S99999999,S00137176,S01013490,S02002516
3,AB1 0AE,AB1 0AE,AB1 0AE,199402,199606,S99999999,S99999999,S12000034,S13002864,S99999999,...,-2.255708,S99999999,NaN,S23000009,5069,S99999999,S99999999,S00138891,S01013856,S02002577
4,AB1 0AF,AB1 0AF,AB1 0AF,199012,199207,S99999999,S99999999,S12000033,S13002843,S99999999,...,-2.258102,S99999999,NaN,S23000009,6253,S99999999,S99999999,S00137241,S01013487,S02002515
5,AB1 0AG,AB1 0AG,AB1 0AG,199012,199207,S99999999,S99999999,S12000033,S13002843,S99999999,...,-2.267513,S99999999,NaN,S23000009,4691,S99999999,S99999999,S00137245,S01013482,S02002515
6,AB1 0AJ,AB1 0AJ,AB1 0AJ,198001,199606,S99999999,S99999999,S12000033,S13002843,S99999999,...,-2.252854,S99999999,NaN,S23000009,6715,S99999999,S99999999,S00137219,S01013490,S02002516
7,AB1 0AL,AB1 0AL,AB1 0AL,198001,199606,S99999999,S99999999,S12000033,S13002843,S99999999,...,-2.254688,S99999999,NaN,S23000009,6253,S99999999,S99999999,S00137184,S01013487,S02002515
8,AB1 0AN,AB1 0AN,AB1 0AN,198001,199606,S99999999,S99999999,S12000033,S13002843,S99999999,...,-2.245483,S99999999,NaN,S23000009,6715,S99999999,S99999999,S00137194,S01013490,S02002516
9,AB1 0AP,AB1 0AP,AB1 0AP,198001,199606,S99999999,S99999999,S12000033,S13002843,S99999999,...,-2.245768,S99999999,NaN,S23000009,6715,S99999999,S99999999,S00137194,S01013490,S02002516

In [6]:
# Export reseult set to Landing.Postcode2AllKinds
# Import SQL library : sqlalchemy

from sqlalchemy import create_engine
from sqlalchemy.types import Integer, String, Numeric, Float

server = 'cic-dw02'
database = 'cicedm01_dev'
engine = create_engine(
    'mssql+pyodbc://'+server+'/'+database+'?driver=ODBC+Driver+17+for+SQL+Server',fast_executemany=True
    # Or ODBC Driver 18
)

dtype_map = {
    "pcd": String(50),
    "pcd2": String(50),
    "pcds": String(50),
    "dointr": String(50),
    "doterm": String(50),
    "oscty": String(50),
    "ced": String(50),
    "oslaua": String(50),
    "osward": String(50),
    "parish": String(50),
    "usertype": String(50),
    "oseast1m": String(50),
    "osnrth1m": String(50),
    "osgrdind": String(50),
    "oshlthau": String(50),
    "nhser": String(50),
    "ctry": String(50),
    "rgn": String(50),
    "streg": String(50),
    "pcon": String(50),
    "eer": String(50),
    "teclec": String(50),
    "ttwa": String(50),
    "pct": String(50),
    "itl": String(50),
    "statsward": String(50),
    "oa01": String(50),
    "casward": String(50),
    "npark": String(50),
    "lsoa01": String(50),
    "msoa01": String(50),
    "ur01ind": String(50),
    "oac01": String(50),
    "oa11": String(50),
    "lsoa11": String(50),
    "msoa11": String(50),
    "wz11": String(50),
    "sicbl": String(50),
    "bua22": String(50),
    "ru11ind": String(50),
    "oac11": String(50),
    "lat": String(50),
    "long": String(50),
    "lep1": String(50),
    "lep2": String(50),
    "pfa": String(50),
    "imd": String(50),
    "calncv": String(50),
    "icb": String(50),
    "oa21": String(50),
    "lsoa21": String(50),
    "msoa21": String(50),
}

df.to_sql(
    name="Postcode2AllKinds",
    con=engine,
    schema="Landing",
    if_exists="replace",
    index=False,
    chunksize = 5000,
    dtype=dtype_map
    #method="multi"   # batch insert
)

-543

In [7]:
df[df["pcd"] == "pcd"].head(10)

Empty DataFrame
Columns: [pcd, pcd2, pcds, dointr, doterm, oscty, ced, oslaua, osward, parish, usertype, oseast1m, osnrth1m, osgrdind, oshlthau, nhser, ctry, rgn, streg, pcon, eer, teclec, ttwa, pct, itl, statsward, oa01, casward, npark, lsoa01, msoa01, ur01ind, oac01, oa11, lsoa11, msoa11, wz11, sicbl, bua22, ru11ind, oac11, lat, long, lep1, lep2, pfa, imd, calncv, icb, oa21, lsoa21, msoa21]
Index: []

[0 rows x 52 columns]

In [9]:
df.size

141050260